name: Auto Test Notebooks

on:
  push:
    branches: [main, dev, pyamares-xmris]
  pull_request:
    branches: [main, pyamares-xmris]

jobs:
  test-notebooks:
    uses: ./.github/workflows/test-notebooks.yml
